In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('March_2021_MPSOV.csv')
df.head()

,ePID,Make,Model,Model_Submodel,Submodel,Year,Vehicle Type,Motorcycle Type,Make_TBC,Make_TBC_inv,Model_TBC,Model_TBC_inv,Model_Submodel_TBC,Model_Submodel_TBC_inv,Submodel_TBC,Submodel_TBC_inv
0,110729864,Husaberg,FC550,FC550,--,2004,Motorcycle,Off-road Motorcycle,husaberg,husaberg,fc550,fc550,fc550,fc550,NaN,NaN
1,110729874,Spencer Bowman Customs,Rock Bottom,Rock Bottom Pro Street ST,Pro Street ST,2009,Motorcycle,Street Motorcycle,spencerbowmancustoms,customsbowmanspencer,rockbottom,bottomrock,rockbottomprostreetst,ststreetprobottomrock,prostreetst,ststreetpro
2,110729884,Tank Sports,Racer,Racer 150,150,2009,Scooter,Scooter,tanksports,sportstank,racer,racer,racer150,150racer,150,150
3,110729904,Derbi,Senda,Senda SM,SM,1999,Motorcycle,Dual Sport Motorcycle,derbi,derbi,senda,senda,sendasm,smsenda,sm,sm
4,110729914,BMC,Notorious,Notorious 918,918,2003,Motorcycle,Street Motorcycle,bmc,bmc,notorious,notorious,notorious918,918notorious,918,918

In [3]:
print('Manufacturer count :',df.Make.nunique())
print('Model count :',df.Model.nunique())
print('Submodel count :',df.Submodel.nunique())

Manufacturer count : 331
Model count : 8919
Submodel count : 6951

In [4]:
df.Make.value_counts()

Yamaha             4801
Honda              3543
Polaris            3145
Kawasaki           3071
Harley-Davidson    3004
                   ...
UBCO                  2
RTX                   1
Cushman II            1
Trifun                1
Arcimoto              1
Name: Make, Length: 331, dtype: int64

In [7]:
def normalize(df, column):
    
    df[f'{column}_TBC'] = df[f'{column}'].str.lower().replace(' ','')
    df[f'{column}_TBC'] = df[f'{column}_TBC'].str.strip()
    df[f'{column}_TBC'] = df[f'{column}_TBC'].str.replace('\s','')
    df[f'{column}_TBC'] = df[f'{column}_TBC'].str.replace('-','')
    df[f'{column}_TBC'] = df[f'{column}_TBC'].str.replace('_','')
    
    df[f'{column}_TBC_inv'] = df[f'{column}'].apply(lambda x: "".join(list(reversed(x.split()))))
    df[f'{column}_TBC_inv'] = df[f'{column}_TBC_inv'].str.lower()
    df[f'{column}_TBC_inv'] = df[f'{column}_TBC_inv'].str.replace('\s','')
    df[f'{column}_TBC_inv'] = df[f'{column}_TBC_inv'].str.replace('-','')
    df[f'{column}_TBC_inv'] = df[f'{column}_TBC_inv'].str.replace('_','')
    df[f'{column}_TBC_inv'] = df[f'{column}_TBC_inv'].str.replace(' ','')
    
    return df

In [9]:
columns_to_implement = ['Make','Model','Model_Submodel','Submodel']

for col in columns_to_implement:
    df = normalize(df, col)
df.head()

<ipython-input-7-2c37c6a7ed02>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df[f'{column}_TBC'] = df[f'{column}_TBC'].str.replace('\s','')
<ipython-input-7-2c37c6a7ed02>:11: FutureWarning: The default value of regex will change from True to False in a future version.
  df[f'{column}_TBC_inv'] = df[f'{column}_TBC_inv'].str.replace('\s','')

,ePID,Make,Model,Model_Submodel,Submodel,Year,Vehicle Type,Motorcycle Type,Make_TBC,Make_TBC_inv,Model_TBC,Model_TBC_inv,Model_Submodel_TBC,Model_Submodel_TBC_inv,Submodel_TBC,Submodel_TBC_inv
0,110729864,Husaberg,FC550,FC550,--,2004,Motorcycle,Off-road Motorcycle,husaberg,husaberg,fc550,fc550,fc550,fc550,,
1,110729874,Spencer Bowman Customs,Rock Bottom,Rock Bottom Pro Street ST,Pro Street ST,2009,Motorcycle,Street Motorcycle,spencerbowmancustoms,customsbowmanspencer,rockbottom,bottomrock,rockbottomprostreetst,ststreetprobottomrock,prostreetst,ststreetpro
2,110729884,Tank Sports,Racer,Racer 150,150,2009,Scooter,Scooter,tanksports,sportstank,racer,racer,racer150,150racer,150,150
3,110729904,Derbi,Senda,Senda SM,SM,1999,Motorcycle,Dual Sport Motorcycle,derbi,derbi,senda,senda,sendasm,smsenda,sm,sm
4,110729914,BMC,Notorious,Notorious 918,918,2003,Motorcycle,Street Motorcycle,bmc,bmc,notorious,notorious,notorious918,918notorious,918,918

In [10]:
df.to_csv('March_2021_MPSOV.csv', index=False)